#!/bin/bash

# Restore previously stashed changes
function unstash() {
    git stash pop
}

# On error, restore stash
trap unstash ERR

# exit on non-zero code
set -e

# make sure that unstaged changes are not used during the hook
git stash push --include-untracked --keep-index

# Run ESLint & Prettier checks
echo "[Better-Moodle Pre-Commit]: Running lint:check"
eslint_cache=$(mktemp)
yarn lint:check --cache-location="$eslint_cache"
rm "$eslint_cache"

echo "[Better-Moodle Pre-Commit]: Running prettier:check"
prettier_cache="$(mktemp).json"
yarn prettier:check --cache-location="$prettier_cache"
rm "$prettier_cache"

# Check if the JSON schemas are in sync with their TS-Definitions
echo "[Better-Moodle Pre-Commit]: Checking for up-to-date JSON schemas"
yarn config:scheme
git diff --exit-code --quiet

# TODO: Evaluate if we always want to build on uzl or also build other configurations?
# This shouldn't change much as tsc is always run on the whole codebase
# However an env variable that defaults to uzl shouldn't hurt too.

echo "[Better-Moodle Pre-Commit]: Building once for uzl"
yarn build uzl

echo "[Better-Moodle Pre-Commit]: Testing source code on uzl"
export BM_NO_COVERAGE="true"
yarn test:src uzl

# TODO Evaluate if we also want to test userscript?

# Finally restore stash
unstash
