export enum WeatherCode {
    UNKNOWN,

    CLEAR,
    FEW_CLOUDS,
    SCATTERED_CLOUDS,
    BROKEN_CLOUDS,
    OVERCAST_CLOUDS,

    MIST,
    FOG,
    FREEZING_FOG,
    DUST,
    SAND,
    HAZE,
    SMOKE,
    VOLCANIC_ASH,

    WIND,
    SQUALLS,
    TORNADO,

    LIGHT_SNOW,
    MODERATE_SNOW,
    HEAVY_SNOW,

    LIGHT_RAIN,
    MODERATE_RAIN,
    HEAVY_RAIN,

    LIGHT_DRIZZLE,
    MODERATE_DRIZZLE,
    HEAVY_DRIZZLE,

    LIGHT_SLEET,
    MODERATE_SLEET,

    LIGHT_THUNDERSTORM,
    MODERATE_THUNDERSTORM,
    HEAVY_THUNDERSTORM,

    LIGHT_FREEZING_RAIN,
    MODERATE_FREEZING_RAIN,

    LIGHT_FREEZING_DRIZZLE,
    MODERATE_FREEZING_DRIZZLE,
    HEAVY_FREEZING_DRIZZLE,

    LIGHT_RAIN_SHOWERS,
    MODERATE_RAIN_SHOWERS,
    HEAVY_RAIN_SHOWERS,

    LIGHT_SLEET_SHOWERS,
    MODERATE_SLEET_SHOWERS,

    LIGHT_DRIZZLE_SHOWERS,
    MODERATE_DRIZZLE_SHOWERS,
    HEAVY_DRIZZLE_SHOWERS,

    LIGHT_SNOW_SHOWERS,
    MODERATE_SNOW_SHOWERS,
    HEAVY_SNOW_SHOWERS,

    LIGHT_HAIL_SHOWERS,
    MODERATE_HAIL_SHOWERS,

    LIGHT_THUNDERSTORM_WITH_DRIZZLE,
    MODERATE_THUNDERSTORM_WITH_DRIZZLE,
    HEAVY_THUNDERSTORM_WITH_DRIZZLE,

    LIGHT_THUNDERSTORM_WITH_RAIN,
    MODERATE_THUNDERSTORM_WITH_RAIN,
    HEAVY_THUNDERSTORM_WITH_RAIN,

    LIGHT_THUNDERSTORM_WITH_SNOW,
    MODERATE_THUNDERSTORM_WITH_SNOW,

    MODERATE_THUNDERSTORM_WITH_HAIL,
    HEAVY_THUNDERSTORM_WITH_HAIL,

    MODERATE_THUNDERSTORM_WITH_RAIN_SHOWERS,

    EXTREME_SNOW,
    EXTREME_RAIN,

    PATCHY_RAIN_NEARBY,
    PATCHY_SNOW_NEARBY,
    PATCHY_SLEET_NEARBY,
    PATCHY_FREEZING_DRIZZLE_NEARBY,
    THUNDERY_OUTBREAKS_NEARBY,
}
