defaultSemverRangePrefix: ''

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
    - checksum: e5e6e2885ab0e6521b70b0af7c6d8ca2c75dcae2403706fc4600a783b339a6530a476dafb9450c9436ca4050eb6bdee9b62e6e2cebfecf1e81dd709a2480dc07
      path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
      spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
    - checksum: f8ce3a541a57481f6213647cfe7ac8555d87cb1fc23a73a102e64e12be07f603826d822f4d0285333400f0f15baed92510c33dcce75dde2953b2811e36efa012
      path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
      spec: 'https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js'

yarnPath: .yarn/releases/yarn-4.10.3.cjs

gitHooksPath: .git-hooks
