// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
    BaseTranslation as BaseTranslationType,
    LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'de';

export type Locales = 'de' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
    settings: {
        /**
         * N​e​u​!
         */
        newBadge: string;
        modal: {
            /**
             * E​i​n​s​t​e​l​l​u​n​g​e​n
             */
            title: string;
            /**
             * Z​u​ ​d​e​n​ ​M​o​o​d​l​e​ ​E​i​n​s​t​e​l​l​u​n​g​e​n
             */
            moodleSettings: string;
            /**
             * i​n​s​t​a​l​l​i​e​r​t​e​ ​V​e​r​s​i​o​n
             */
            installedVersion: string;
            /**
             * a​k​t​u​e​l​l​s​t​e​ ​V​e​r​s​i​o​n
             */
            latestVersion: string;
            /**
             * U​p​d​a​t​e​ ​i​n​s​t​a​l​l​i​e​r​e​n
             */
            updateBtn: string;
            /**
             * E​i​n​s​t​e​l​l​u​n​g​e​n​ ​i​m​p​o​r​t​i​e​r​e​n
             */
            import: string;
            /**
             * E​i​n​s​t​e​l​l​u​n​g​e​n​ ​e​x​p​o​r​t​i​e​r​e​n
             */
            export: string;
        };
        /**
         * C​h​a​n​g​e​l​o​g
         */
        changelog: string;
    };
};

export type TranslationFunctions = {
    settings: {
        /**
         * Neu!
         */
        newBadge: () => LocalizedString;
        modal: {
            /**
             * Einstellungen
             */
            title: () => LocalizedString;
            /**
             * Zu den Moodle Einstellungen
             */
            moodleSettings: () => LocalizedString;
            /**
             * installierte Version
             */
            installedVersion: () => LocalizedString;
            /**
             * aktuellste Version
             */
            latestVersion: () => LocalizedString;
            /**
             * Update installieren
             */
            updateBtn: () => LocalizedString;
            /**
             * Einstellungen importieren
             */
            import: () => LocalizedString;
            /**
             * Einstellungen exportieren
             */
            export: () => LocalizedString;
        };
        /**
         * Changelog
         */
        changelog: () => LocalizedString;
    };
};

export type Formatters = {};
