name: 📜 PR Summary
description: Update or create a PR comment with sectioned content

inputs:
    pr-number:
        description: 'Pull Request number'
        required: true
    section:
        description: 'Section name in Markdown format'
        required: true
    content:
        description: 'Section content in Markdown format'
        required: true

runs:
    using: 'composite'
    steps:
        - name: '✏️ Update or create comment'
          shell: bash
          run: |
              COMMENT_URL=$(gh pr view ${{ inputs.pr-number }} --json comments --jq '[.comments[] | select(.body | startswith("<!-- Better-Moodle PR-Summary -->"))][0] .url')
              TITLE="<summary><h2>${{ inputs.section }}</h2></summary>"
              START_COMMENT="<!-- ${{ inputs.section }} -->"
              END_COMMENT="<!-- #${{ inputs.section }} -->"
              RUN="Run: [\`${{github.run_id}}/${{github.run_attempt}}\`](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/attempts/${{github.run_attempt}})"

              if [ -z "$COMMENT_URL" ]; then
                gh pr comment ${{ inputs.pr-number }} --body "<!-- Better-Moodle PR-Summary -->
              $START_COMMENT
              <details>
              $TITLE

              $RUN

              ${{ inputs.content }}
              </details>
              $END_COMMENT"
              else
                COMMENT_ID=$(echo "$COMMENT_URL" | sed 's/.*-\([0-9]*\)$/\1/')

                OLD_BODY=$(gh pr view ${{ inputs.pr-number }} --json comments --jq '.comments[] | select(.url == "$COMMENT_URL") | .body')
                DEL_BODY=$(echo $OLD_BODY | sed "s/$START_COMMENT.*$END_COMMENT//")
                NEW_BODY="${DEL_BODY}
              $START_COMMENT
              <details>
              $TITLE

              $RUN

              ${{ inputs.content }}
              </details>
              $END_COMMENT"

                gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{github.repository}}/issues/comments/"$COMMENT_ID" -f body="$NEW_BODY"
              fi
          env:
              GH_TOKEN: ${{ github.token }}
