import { type Context } from '../context';
import monkey from 'vite-plugin-monkey';
import { scriptCopyright } from '../utils/copyright';

/**
 * @param ctx
 */
export default function (ctx: Context) {
    return monkey({
        entry: 'src/core.tsx',
        userscript: {
            'name': ctx.userscript.name,
            'namespace': ctx.userscript.namespace,
            'version': ctx.version,
            'author': ctx.userscript.authors.join(', '),
            'description': ctx.userscript.description,
            'homepage': ctx.userscript.homepage,
            'homepageURL': ctx.userscript.homepage,
            'icon': ctx.userscript.icon,
            'updateURL': ctx.userscript.updateURL,
            'downloadURL': ctx.userscript.downloadURL,
            'match': ctx.userscript.match,
            'run-at': 'document-start',
            'connect': ctx.userscript.connect,
            'require': ctx.userscript.require.list(),
        },
        clientAlias: 'GM',
        build: {
            fileName: ctx.dist.script,
            metaFileName: ctx.dist.meta,
            autoGrant: true,
        },
        /**
         * Adds the copyright notice and a eslint global comment to the userscript
         * @param root0 - information about the userscript, also containing the header
         * @param root0.userscript - the userscript header as generated by vite-plugin-monkey
         * @returns the userscript header plus preamble
         */
        generate({ userscript: header }) {
            // userscript header
            // Copyright
            // globals
            // allow redeclaring globals (otherwise polyfills may fail) => for the self-written code, this is already done via TS so it is okay to use this rule like this
            return `
${header}

${scriptCopyright(ctx)}

/* global global, globalThis, ActiveXObject, Iterator, M, requirejs, DarkReader */
/* eslint no-redeclare: ["error", { "builtinGlobals": false }] */
`.trim();
        },
    });
}
